### ISSUE TITLE
Jenkins job to install Satellite 5.x

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/transitions#1]
We need a Jenkins job that will install Satellite 5.x (where x could be 6 or 7) using our ``automation-tools`` tool.

**Comment by lpramuk** [comment]
initial version of jenkins job was pushed into SatelliteQE/robottelo-ci repo

**Comment by Ichimonji10** [comment]
https://github.com/SatelliteQE/robottelo-ci/commit/302ea76b0816e0eea27c8b2ab7c1e80f9aca2040

**Comment by lpramuk** [comment]
Initial version from Apr 17, 2015 had solved this issue
